export const EZABATU_PROIEKTUA = "EZABATU_PROIEKTUA";
export const JASO_PROIEKTUAK = "JASO_PROIEKTUAK";
export const JASO_FITXATEGIAK = "JASO_FITXATEGIAK";
export const FITXATEGIA_GEHITU = "FITXATEGIA_GEHITU";
export const EZABATU_FITXATEGIA = "EZABATU_FITXATEGIA";
export const JASO_ATAZA_MOTAK = "JASO_ATAZA_MOTAK";
export const JASO_DATU_MOTAK = "JASO_DATU_MOTAK";
export const HAUTATU_PROIEKTUA = "HAUTATU_PROIEKTUA";
export const ADD_LEAD = "ADD_LEAD";
export const PROIEKTUA_ALDATU = "PROIEKTUA_ALDATU";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const JASO_AZTERKETAK = "JASO_AZTERKETAK";
export const GEHITU_AZTERKETA = "GEHITU_AZTERKETA";
export const AZTERKETA_ALDATU = "AZTERKETA_ALDATU";
export const AZTERKETA_EZABATU = "AZTERKETA_EZABATU";
export const EZABATU_PROIEKTUKO_AZTERKETAK = "EZABATU_PROIEKTUKO_AZTERKETAK";



