FROM python:3.6
MAINTAINER Filipe Garcia <filipe.garcia@seedstarslabs.com>

ENV PYTHONUNBUFFERED 1

COPY ./docker/django/wsgi-entrypoint.sh /wsgi-entrypoint.sh
COPY requirements.txt /django/

WORKDIR /django

RUN chmod +x /wsgi-entrypoint.sh
ENTRYPOINT ["/wsgi-entrypoint.sh"]

RUN pip install pip
RUN pip install -r requirements.txt
